/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.storemanager;

import com.lentrix.storemanager.db.ItemController;
import com.lentrix.storemanager.models.ItemModel;
import java.sql.SQLException;
/**
 *
 * @author lentrix
 */
public class MerchandiseEntryDialog extends javax.swing.JDialog {
    ItemModel item;
    /**
     * Creates new form MerchandiseEntryDialog
     */
    public MerchandiseEntryDialog(java.awt.Frame parent, boolean modal, ItemModel item) {
        super(parent, modal);
        this.item = item;
        initComponents();
        
        if(item!=null) {
            barCodeField.setText(item.getBarCode());
            itemNameField.setText(item.getItemName());
            itemDescriptionField.setText(item.getItemDescription());
            volumeField.setText(item.getVolume());
            wholesaleUnitField.setText(item.getWsUnit());
            wholesalePriceField.setText(String.format("%,.2f", item.getWsPrice()));
            wholesaleQtyField.setText(String.valueOf(item.getWsQty()));
            retailUnitField.setText(item.getRtUnit());
            retailPriceField.setText(String.format("%,.2f", item.getRtPrice()));
            quantityField.setText(String.valueOf(item.getQty()));
        }
    }
    
    private boolean validateFields() {
        if(barCodeField.getText().isBlank()){
            Helper.error("Barcode cannot be blank", this);
            return false;
        }
        
        if(itemNameField.getText().isBlank()) {
            Helper.error("Item name cannot be blank", this);
            return false;
        }
        
        if(itemDescriptionField.getText().isBlank()) {
            Helper.error("Item description cannot be blank", this);
            return false;
        }
        
        if(volumeField.getText().isBlank()) {
            Helper.error("Item volume cannot be blank", this);
            return false;
        }
        
        if(wholesaleUnitField.getText().isBlank()) {
            Helper.error("Item wholesale unit cannot be blank", this);
            return false;
        }
        
        if(wholesaleQtyField.getText().isBlank()) {
            Helper.error("Item Wholesale Qty cannot be blank", this);
            return false;
        }
        
        if(wholesalePriceField.getText().isBlank()) {
            Helper.error("Item Wholesale price cannot be blank", this);
            return false;
        }
        
        if(retailUnitField.getText().isBlank()) {
            Helper.error("Item Retail unit cannot be blank", this);
            return false;
        }
        
        if(retailPriceField.getText().isBlank()) {
            Helper.error("Item Retail price cannot be blank", this);
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        barCodeField = new javax.swing.JTextField();
        itemNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemDescriptionField = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        volumeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        wholesaleUnitField = new javax.swing.JTextField();
        wholesaleQtyField = new javax.swing.JTextField();
        wholesalePriceField = new javax.swing.JTextField();
        retailUnitField = new javax.swing.JTextField();
        retailPriceField = new javax.swing.JTextField();
        saveChangesButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Merchandise Data Entry");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Merchandise Data Entry");

        jLabel2.setText("Bar Code:");

        jLabel3.setText("Item Name:");

        jLabel4.setText("Item Description:");

        itemDescriptionField.setColumns(20);
        itemDescriptionField.setRows(5);
        jScrollPane1.setViewportView(itemDescriptionField);

        jLabel5.setText("Volume:");

        jLabel6.setText("Wholesale Unit:");

        jLabel7.setText("Wholesale Qty:");

        jLabel8.setText("Wholesale Price:");

        jLabel9.setText("Retail Unit:");

        jLabel10.setText("Retail Price:");

        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Quantity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retailUnitField)
                            .addComponent(wholesalePriceField)
                            .addComponent(wholesaleQtyField)
                            .addComponent(volumeField)
                            .addComponent(wholesaleUnitField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retailPriceField)
                            .addComponent(quantityField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveChangesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barCodeField)
                            .addComponent(itemNameField)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(barCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(volumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(wholesaleUnitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(wholesaleQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(wholesalePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(retailUnitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(retailPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangesButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(582, 626));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        try {
            if(item==null) {

                item = new ItemModel(
                        -1, barCodeField.getText(),
                        itemNameField.getText(),
                        itemDescriptionField.getText(),
                        volumeField.getText(),
                        wholesaleUnitField.getText(),
                        Integer.parseInt(wholesaleQtyField.getText()),
                        Float.parseFloat(wholesalePriceField.getText()),
                        retailUnitField.getText(),
                        Float.parseFloat(retailPriceField.getText()),
                        Integer.parseInt(quantityField.getText())
                );
                
                ItemController.insert(item);

            }else {
                item.setBarCode(barCodeField.getText());
                item.setItemName(itemNameField.getText());
                item.setItemDescription(itemDescriptionField.getText());
                item.setVolume(volumeField.getText());
                item.setWsUnit(wholesaleUnitField.getText());
                item.setWsQty(Integer.parseInt(wholesaleQtyField.getText()));
                item.setWsPrice(Float.parseFloat(wholesalePriceField.getText()));
                item.setRtUnit(retailUnitField.getText());
                item.setRtPrice(Float.parseFloat(retailPriceField.getText()));
                item.setQty(Integer.parseInt(quantityField.getText()));
                ItemController.update(item);
            }
            
            this.dispose();
        }catch(NumberFormatException ex) {
            Helper.error("There are some invalid numeric entries.", this);
        }catch(SQLException ex) {
            Helper.error(ex.getMessage(), this);
        }
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barCodeField;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea itemDescriptionField;
    private javax.swing.JTextField itemNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField retailPriceField;
    private javax.swing.JTextField retailUnitField;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JTextField volumeField;
    private javax.swing.JTextField wholesalePriceField;
    private javax.swing.JTextField wholesaleQtyField;
    private javax.swing.JTextField wholesaleUnitField;
    // End of variables declaration//GEN-END:variables
}
