/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.storemanager;

import com.lentrix.storemanager.db.ItemController;
import com.lentrix.storemanager.db.SalesController;
import com.lentrix.storemanager.db.SalesItemController;
import com.lentrix.storemanager.models.CustomerModel;
import com.lentrix.storemanager.models.ItemModel;
import com.lentrix.storemanager.models.SalesItemModel;
import com.lentrix.storemanager.models.SalesModel;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentrix
 */
public class POSTerminal extends javax.swing.JFrame {
    List<SalesItemModel> salesItems;
    boolean isWholesale;
    CustomerModel customer;
    /**
     * Creates new form POSTerminal
     */
    public POSTerminal() {
        initComponents();
        GraphicsEnvironment graphics =
        GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice device = graphics.getDefaultScreenDevice();
        device.setFullScreenWindow(this);
        barCodeField.grabFocus();
        cashierLabel.setText("Cashier: " + Helper.currentUser.getFullname());
        
        salesItems = new ArrayList<SalesItemModel>();
        
        isWholesale = false;
        customer = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        quantityButton = new javax.swing.JButton();
        wholesaleRetailButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        finalizeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        subTotalLabel = new javax.swing.JLabel();
        cashierLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        barCodeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(214, 243, 246));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 5));

        jPanel2.setLayout(new java.awt.GridLayout(6, 1, 0, 5));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(clearButton);

        quantityButton.setText("Quantity");
        quantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityButtonActionPerformed(evt);
            }
        });
        jPanel2.add(quantityButton);

        wholesaleRetailButton.setText("Wholesale / Retail");
        wholesaleRetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wholesaleRetailButtonActionPerformed(evt);
            }
        });
        jPanel2.add(wholesaleRetailButton);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(removeButton);

        finalizeButton.setText("Finalize");
        finalizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(finalizeButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("S & S Superstore | Point of Sale Terminal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        subTotalLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        subTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        subTotalLabel.setText("Sub Total: P0.00");

        cashierLabel.setText("Cashier: Name of Cashier");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266)
                .addComponent(subTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotalLabel)
                    .addComponent(cashierLabel))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel2.setText("Bar Code:");

        barCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barCodeFieldActionPerformed(evt);
            }
        });
        barCodeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barCodeFieldKeyReleased(evt);
            }
        });

        jLabel3.setText("Quantity Type: Wholesale");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(barCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jTable1.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(24);
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Administration");

        jMenuItem1.setText("Open Administration");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaction");

        jMenuItem3.setText("Clear Entries");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Change Quantity");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Set Customer");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Remove Item");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Finalize Transaction");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void barCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barCodeFieldActionPerformed
        try {
            ItemModel item = ItemController.findCode(barCodeField.getText());
            if(item!=null) {
                SalesItemModel salesItem = new SalesItemModel(-1, item, 1, true);
                salesItem.getPrice();
                
                salesItems.add(salesItem);
                refreshTable();
                barCodeField.setText(null);
                barCodeField.grabFocus();
            }else {
                Helper.error("The barcode cannot be found.", this);
            }
        }catch(SQLException ex) {
            Helper.error(ex.getMessage(), this);
        }
    }//GEN-LAST:event_barCodeFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void quantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityButtonActionPerformed
        changeQty();
    }//GEN-LAST:event_quantityButtonActionPerformed

    private void barCodeFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barCodeFieldKeyReleased
        switch(evt.getKeyCode()) {
            case 112: clear(); break;
            case 113: changeQty(); break;
            case 115: remove(); break;
            case 114: toggleWholesale(); break;
        }
    }//GEN-LAST:event_barCodeFieldKeyReleased

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        remove();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void wholesaleRetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wholesaleRetailButtonActionPerformed
        toggleWholesale();
    }//GEN-LAST:event_wholesaleRetailButtonActionPerformed

    private void finalizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeButtonActionPerformed
        finalizeSales();
    }//GEN-LAST:event_finalizeButtonActionPerformed

    private void remove() {
        int row = jTable1.getSelectedRow();
        row = row==-1?salesItems.size()-1:row;
        
        SalesItemModel salesItem = salesItems.get(row);
        
        int res = JOptionPane.showConfirmDialog(this, "Do you want to remove this item " + salesItem.getItem().getItemName() + "?", "Remove?", JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION) {
            salesItems.remove(row);
            refreshTable();
        }else {
            barCodeField.grabFocus();
        }
    }
    
    private void toggleWholesale() {
        int row = jTable1.getSelectedRow();
        row = row==-1?salesItems.size()-1:row;
        
        SalesItemModel salesItem = salesItems.get(row);
        
        salesItem.setIsWholeSale(!salesItem.isIsWholeSale());
        salesItem.renewPrice();
        
        refreshTable();
    }
    
    private void clear() {
        int res = JOptionPane.showConfirmDialog(this, "Do you want to clear all the items?", "Clear All?", JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION) {
            salesItems.clear();
            refreshTable();
        }
    }
    
    private void changeQty() {
        int row = jTable1.getSelectedRow();
        row = row==-1?salesItems.size()-1:row;
        try {
            int qty = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter new quantity:"));
            
            SalesItemModel salesItem = salesItems.get(row);
            
            salesItem.setQty(qty);
            
            refreshTable();
        }catch(NumberFormatException ex) {
            Helper.error("You entered an valid quantity value.", this);
        }
    }
    
    private void finalizeSales() {
        try {
            
            //Create a new dialog to ask for cash tender
            //transfer the code below to the appropriate method
            //in the dialog and continue on with the finalization process
            //including printing of receipt.
            SalesModel sales = SalesController.create();
            SalesItemController.insert(salesItems, sales.getId());
            
        }catch(SQLException ex) {
            Helper.error(ex.getMessage(), this);
        }
    }
    
    /**
     * Change customer for future additional feature
     */
    private void changeCustomer() {
        
    }
    
    private void refreshTable() {
        String[] headers = {"Item", "Description", "Price", "Qty", "Amount"};
        DefaultTableModel model = new DefaultTableModel(headers, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        float subTotal = 0f;
        
        for(SalesItemModel salesItem: salesItems) {
            float price = salesItem.isIsWholeSale() ? salesItem.getItem().getWsPrice() : salesItem.getItem().getRtPrice();
            float amount = price * salesItem.getQty();
            subTotal += amount;
            model.addRow(new Object[] {
                salesItem.getItem().getItemName(),
                salesItem.getItem().getItemDescription(),
                String.format("%,.2f", price),
                salesItem.getQty(),
                String.format("%,.2f", amount)
            });
        }
        
        jTable1.setModel(model);
        
        jTable1.getColumnModel().getColumn(0).setMinWidth(150);
        jTable1.getColumnModel().getColumn(1).setMinWidth(350);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        
        subTotalLabel.setText(String.format("Sub Total: %,.2f", subTotal));
        
        barCodeField.grabFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barCodeField;
    private javax.swing.JLabel cashierLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton finalizeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton quantityButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JButton wholesaleRetailButton;
    // End of variables declaration//GEN-END:variables
}
